zabbixserver:
  replicaCount: 3
  extraEnv:
    - name: "ZBX_AUTONODEADDRESS"
      value: "fqdn"
    - name: "ZBX_AUTOHANODENAME"
      value: "fqdn"

db_access:
  secret_name: false
  DB_SERVER_PORT: "5432"
  POSTGRES_DB: "zabbix"

postgresql:
  enabled: false

zabbixweb:
  service:
    type: LoadBalancer
